#pragma once

#define HIDE_DRIVER 0x8101
#define IOCTL_HIDE_PROCESSES CTL_CODE(HIDE_DRIVER, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNHIDE_PROCESSES CTL_CODE(HIDE_DRIVER, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SHOW_HIDDEN_PROCESSES CTL_CODE(HIDE_DRIVER, 0x803, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)